-- Insert sample users
INSERT INTO app_user (id, username, email, password) VALUES
                                                         (1, 'john_doe', 'john.doe@example.com', 'password123'),
                                                         (2, 'jane_smith', 'jane.smith@example.com', 'securePass!1'),
                                                         (3, 'michael_lee', 'michael.lee@example.com', 'mypassword456'),
                                                         (4, 'lisa_white', 'lisa.white@example.com', 'mySecretPass7'),
                                                         (5, 'emily_brown', 'emily.brown@example.com', 'password!123');

-- Insert sample portfolios
INSERT INTO portfolio (id, title, theme, about, work_experience, projects, education, skills, user_id) VALUES
                                                                                                           (1, 'John''s Professional Site', 'dark',
                                                                                                            'Experienced software engineer with a passion for developing scalable web applications.',
                                                                                                            'Senior Software Engineer at TechCorp (2020–Present)\nSoftware Developer at CodeFactory (2017–2020)',
                                                                                                            'E-commerce Platform, Inventory Management System',
                                                                                                            'B.S. in Computer Science, Stanford University (2017)',
                                                                                                            'Java, Spring Boot, React, SQL',
                                                                                                            1),
                                                                                                           (2, 'Jane''s Design Portfolio', 'light',
                                                                                                            'Creative UX/UI designer with a knack for delivering intuitive user experiences.',
                                                                                                            'Lead UX Designer at Creatify (2019–Present)\nJunior Designer at PixelPerfect (2016–2019)',
                                                                                                            'Mobile Banking App, Food Delivery App',
                                                                                                            'B.A. in Design, Rhode Island School of Design (2016)',
                                                                                                            'Adobe XD, Figma, HTML/CSS',
                                                                                                            2),
                                                                                                           (3, 'Michael''s Dev Showcase', 'dark',
                                                                                                            'Full-stack developer specializing in backend services and API development.',
                                                                                                            'Backend Developer at DataStream (2021–Present)\nIntern at BuildIt (2018–2021)',
                                                                                                            'Real-Time Chat Application, REST API for E-Learning Platform',
                                                                                                            'B.S. in Information Technology, MIT (2021)',
                                                                                                            'Node.js, Express, MongoDB, TypeScript',
                                                                                                            3),
                                                                                                           (4, 'Lisa''s Data Science Hub', 'light',
                                                                                                            'Data scientist with expertise in predictive analytics and machine learning models.',
                                                                                                            'Data Scientist at AnalyzeNow (2020–Present)\nResearch Assistant at DataLab (2018–2020)',
                                                                                                            'Fraud Detection System, Customer Segmentation Model',
                                                                                                            'M.S. in Data Science, University of California, Berkeley (2020)',
                                                                                                            'Python, TensorFlow, SQL, R',
                                                                                                            4),
                                                                                                           (5, 'Emily''s Coding Journey', 'dark',
                                                                                                            'Junior software developer passionate about learning and growing in the tech industry.',
                                                                                                            'Software Engineer Intern at StartUpHub (2023–Present)',
                                                                                                            'Portfolio Website, Todo App',
                                                                                                            'B.S. in Software Engineering, Carnegie Mellon University (2023)',
                                                                                                            'HTML, CSS, JavaScript, Java',
                                                                                                            5);
